on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

jobs:
  build_css:
    runs-on: ubuntu-latest
    env:
      source: public/dist/assets
      destination: test/assets/website-2021/pr-${{ github.event.number }}/
    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          persist-credentials: false

      - name: Upload to cdn.w3.org bucket
        if: success()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
        run:
          aws s3 sync --no-progress ${{ env.source }} s3://cdn-dev.w3.org/${{ env.destination }}
