name: Analytics Tests
 
on:
  push:
    paths:
      - 'analytics/**/**'
 
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: echo
        run: echo "foobar"
